<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>joydex-secrets</AssemblyName>
    <RootNamespace>Joydex.Secrets.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Joydex.Secrets\Joydex.Secrets.csproj" />
  </ItemGroup>
</Project>
