<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Joydex.Core\Joydex.Core.csproj" />
    <ProjectReference Include="..\Joydex.Windows\Joydex.Windows.csproj" />
  </ItemGroup>

  <ItemGroup Condition="Exists('Assets\cm3-button-map.png')">
    <Content Include="Assets\cm3-button-map.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup Condition="Exists('..\..\docs\images\joydex-button-map_vpc-constellation-alpha-warbrd.png')">
    <Content Include="..\..\docs\images\joydex-button-map_vpc-constellation-alpha-warbrd.png"
             Link="Assets\alpha-warbrd-button-map.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

</Project>
