<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\VirpilCodexPad.Core\VirpilCodexPad.Core.csproj" />
    <ProjectReference Include="..\VirpilCodexPad.Windows\VirpilCodexPad.Windows.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

</Project>
