<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Joydex.SecretsHost</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Joydex.Secrets\Joydex.Secrets.csproj" />
  </ItemGroup>
</Project>
